# Generated by Django 6.0.1 on 2026-02-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_destino_mensaje_rentaauto_vuelo_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
        migrations.AddField(
            model_name='destino',
            name='mensaje_reserva',
            field=models.TextField(blank=True, help_text='Mensaje predefinido para reserva/contacto'),
        ),
        migrations.AddField(
            model_name='destino',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='URL del PDF con información detallada del destino', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='mensaje_reserva',
            field=models.TextField(blank=True, help_text='Mensaje predefinido para reserva/contacto'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='URL del PDF con información detallada del hotel', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='rentaauto',
            name='mensaje_reserva',
            field=models.TextField(blank=True, help_text='Mensaje predefinido para reserva/contacto'),
        ),
        migrations.AddField(
            model_name='rentaauto',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='URL del PDF con información detallada del auto', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='mensaje_reserva',
            field=models.TextField(blank=True, help_text='Mensaje predefinido para reserva/contacto'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='URL del PDF con información detallada del vuelo', max_length=500, null=True),
        ),
    ]
