# Generated by Django 6.0.1 on 2026-02-03 15:49

import servicios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_delete_mensaje_destino_mensaje_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='URL del PDF de Google Drive (se convertirá a /preview automáticamente)', max_length=500, null=True, validators=[servicios.models.validate_google_drive_pdf]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='URL del PDF de Google Drive (se convertirá a /preview automáticamente)', max_length=500, null=True, validators=[servicios.models.validate_google_drive_pdf]),
        ),
        migrations.AlterField(
            model_name='rentaauto',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='URL del PDF de Google Drive (se convertirá a /preview automáticamente)', max_length=500, null=True, validators=[servicios.models.validate_google_drive_pdf]),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='URL del PDF de Google Drive (se convertirá a /preview automáticamente)', max_length=500, null=True, validators=[servicios.models.validate_google_drive_pdf]),
        ),
    ]
