# Generated by Django 6.0.1 on 2026-02-03 16:26

import django.db.models.deletion
import servicios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_alter_destino_pdf_url_alter_hotel_pdf_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Aerolínea',
                'verbose_name_plural': 'Aerolíneas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PaisRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_pais', models.CharField(blank=True, help_text='Código ISO del país (ej: USA, ECU)', max_length=3)),
                ('bandera_url', models.URLField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'País/Destino de Región',
                'verbose_name_plural': 'Países/Destinos de Región',
                'ordering': ['region', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('caribe', 'Caribe'), ('sudamerica', 'Sudamérica'), ('centroamerica', 'Centroamérica'), ('norteamerica', 'Norteamérica'), ('europa', 'Europa'), ('medio_oriente', 'Medio Oriente'), ('africa', 'África'), ('asia', 'Asia'), ('ecuador', 'Ecuador')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PaqueteTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del paquete para el card', max_length=200)),
                ('subtitulo', models.CharField(blank=True, help_text='Subtítulo o info adicional (ej: Enero a Diciembre)', max_length=200)),
                ('imagen_url', models.URLField(help_text='Imagen principal del card', max_length=500)),
                ('descripcion_corta', models.TextField(help_text='Descripción breve para el card', max_length=500)),
                ('ciudad_destino', models.CharField(blank=True, help_text='Ciudad específica del destino', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio desde', max_digits=10)),
                ('moneda', models.CharField(default='USD', max_length=3)),
                ('tipo_paquete', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('promo', 'Promo'), ('oferta', 'Oferta'), ('todo_incluido', 'Todo Incluido'), ('aventura', 'Aventura'), ('luna_miel', 'Luna de Miel'), ('familiar', 'Familiar'), ('negocios', 'Negocios')], default='vacaciones', max_length=20)),
                ('duracion_noches', models.IntegerField(help_text='Número de noches')),
                ('salidas', models.CharField(help_text='Ej: Quito y Guayaquil', max_length=200)),
                ('fecha_salidas_texto', models.CharField(blank=True, help_text='Ej: 2025 Enero a Diciembre', max_length=100)),
                ('titulo_detalle', models.CharField(blank=True, help_text='Título principal en la página de detalle', max_length=300)),
                ('descripcion_extensa', models.TextField(blank=True, help_text='Descripción completa del paquete')),
                ('temporada', models.CharField(choices=[('baja', 'Temporada Baja'), ('media', 'Temporada Media'), ('alta', 'Temporada Alta')], default='baja', max_length=10)),
                ('tipo_viaje', models.CharField(choices=[('familiar', 'Viajes de familia'), ('pareja', 'Viajes en pareja'), ('amigos', 'Viajes con amigos'), ('solo', 'Viaje solo'), ('negocios', 'Viaje de negocios'), ('aventura', 'Viaje de aventura')], default='familiar', max_length=20)),
                ('precio_aplica_desde', models.DateField(blank=True, help_text='Fecha desde que aplica el precio', null=True)),
                ('precio_aplica_hasta', models.DateField(blank=True, help_text='Fecha hasta que aplica el precio', null=True)),
                ('ubicacion_mapa_url', models.URLField(blank=True, help_text='URL de imagen del mapa', max_length=500, null=True)),
                ('idioma', models.CharField(blank=True, help_text='Ej: Oficial Inglés USA', max_length=100)),
                ('moneda_local', models.CharField(blank=True, help_text='Ej: Dólar Americano', max_length=100)),
                ('lugares_destacados', models.TextField(blank=True, help_text='Lugares destacados separados por comas')),
                ('documentos_requeridos', models.TextField(blank=True, help_text='Ej: Visa Americana. Pasaporte vigente.')),
                ('temperatura', models.CharField(blank=True, help_text='Ej: 23°C - 28°C', max_length=50)),
                ('programa_incluye', models.TextField(blank=True, help_text='Qué incluye el programa')),
                ('no_incluye', models.TextField(blank=True, help_text='Qué NO incluye el paquete')),
                ('como_reservar', models.TextField(blank=True, help_text='Instrucciones para reservar')),
                ('importante', models.TextField(blank=True, help_text='Información importante')),
                ('horarios_vuelo', models.TextField(blank=True, help_text='Horarios de vuelos')),
                ('politicas_equipaje', models.TextField(blank=True, help_text='Políticas de equipaje')),
                ('requisitos_viaje', models.TextField(blank=True, help_text='Requisitos para el viaje')),
                ('formas_pago', models.TextField(blank=True, help_text='Formas de pago aceptadas')),
                ('politica_cancelacion', models.TextField(blank=True, help_text='Política de cancelación')),
                ('incluye_vuelo', models.BooleanField(default=True, help_text='¿Incluye vuelo?')),
                ('incluye_hotel', models.BooleanField(default=True, help_text='¿Incluye hotel?')),
                ('incluye_alimentacion', models.BooleanField(default=False, help_text='¿Incluye alimentación?')),
                ('incluye_traslados', models.BooleanField(default=False, help_text='¿Incluye traslados?')),
                ('incluye_tours', models.BooleanField(default=False, help_text='¿Incluye tours?')),
                ('incluye_seguro', models.BooleanField(default=False, help_text='¿Incluye seguro?')),
                ('pdf_url', models.URLField(blank=True, help_text='URL del PDF de Google Drive (se convertirá a /preview automáticamente)', max_length=500, null=True, validators=[servicios.models.validate_google_drive_pdf])),
                ('mensaje_reserva', models.TextField(blank=True, help_text='Mensaje predefinido para reserva/contacto')),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aerolinea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes', to='servicios.aerolinea')),
                ('pais_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='servicios.paisregion')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='servicios.region')),
            ],
            options={
                'verbose_name': 'Paquete Turístico',
                'verbose_name_plural': 'Paquetes Turísticos',
                'ordering': ['-destacado', '-fecha_creacion'],
            },
            bases=(servicios.models.GoogleDrivePDFMixin, models.Model),
        ),
        migrations.AddField(
            model_name='paisregion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paises', to='servicios.region'),
        ),
        migrations.AlterUniqueTogether(
            name='paisregion',
            unique_together={('region', 'nombre')},
        ),
    ]
