# Generated by Django 6.0.1 on 2026-02-03 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_aerolinea_paisregion_region_paqueteturistico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vuelo',
            options={'ordering': ['aerolinea', 'origen', 'destino'], 'verbose_name': 'Vuelo', 'verbose_name_plural': 'Vuelos'},
        ),
        migrations.AddField(
            model_name='aerolinea',
            name='codigo_iata',
            field=models.CharField(blank=True, help_text='Código IATA de 2-3 letras (ej: AA, LA, AV)', max_length=3),
        ),
        migrations.AddField(
            model_name='aerolinea',
            name='pais_origen',
            field=models.CharField(blank=True, help_text='País de origen de la aerolínea', max_length=100),
        ),
        migrations.AddField(
            model_name='aerolinea',
            name='sitio_web',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='rentaauto',
            name='direccion_especifica',
            field=models.CharField(blank=True, help_text='Dirección específica de recogida', max_length=300),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='aerolinea_nombre',
            field=models.CharField(blank=True, help_text='Nombre de aerolínea (solo si no está en el catálogo)', max_length=100),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='numero_vuelo',
            field=models.CharField(blank=True, help_text='Ej: AA1234', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentaauto',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ubicación (solo si la ciudad no está en el catálogo)', max_length=200),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='aerolinea',
            field=models.ForeignKey(blank=True, help_text='Seleccione la aerolínea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vuelos', to='servicios.aerolinea'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='destino',
            field=models.CharField(blank=True, help_text='Destino (solo si no está en el catálogo de ciudades)', max_length=100),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='origen',
            field=models.CharField(blank=True, help_text='Origen (solo si no está en el catálogo de ciudades)', max_length=100),
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_aeropuerto', models.CharField(blank=True, help_text='Código IATA del aeropuerto principal (ej: GYE, UIO)', max_length=5)),
                ('es_capital', models.BooleanField(default=False)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='servicios.paisregion')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['pais', '-es_capital', 'nombre'],
                'unique_together': {('pais', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='rentaauto',
            name='ciudad',
            field=models.ForeignKey(blank=True, help_text='Ciudad donde está disponible (si está en el catálogo)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autos_renta', to='servicios.ciudad'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='ciudad_destino',
            field=models.ForeignKey(blank=True, help_text='Ciudad de destino (si está en el catálogo)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vuelos_destino', to='servicios.ciudad'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='ciudad_origen',
            field=models.ForeignKey(blank=True, help_text='Ciudad de origen (si está en el catálogo)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vuelos_origen', to='servicios.ciudad'),
        ),
    ]
