# Generated by Django 6.0.1 on 2026-02-03 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_alter_vuelo_options_aerolinea_codigo_iata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentaauto',
            old_name='direccion_especifica',
            new_name='direccion',
        ),
        migrations.RemoveField(
            model_name='rentaauto',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='aerolinea_nombre',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='ciudad_destino',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='ciudad_origen',
        ),
        migrations.AlterField(
            model_name='rentaauto',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos_renta', to='servicios.ciudad'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='aerolinea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos', to='servicios.aerolinea'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_destino', to='servicios.ciudad'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_origen', to='servicios.ciudad'),
        ),
    ]
