# Generated by Django 6.0.1 on 2026-02-10 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_rename_direccion_especifica_rentaauto_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paqueteturistico',
            name='ciudad_destino',
            field=models.ForeignKey(blank=True, help_text='Ciudad específica del destino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes', to='servicios.ciudad'),
        ),
    ]
