# Generated by Django 6.0.1 on 2026-02-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_cambiar_ciudad_destino_a_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='paqueteturistico',
            name='duracion_dias',
            field=models.IntegerField(default=1, help_text='Número de días'),
        ),
    ]
