# Generated by Django 6.0.1 on 2026-02-18 17:01

import servicios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_paqueteturistico_duracion_dias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vuelo',
            options={'ordering': ['-destacado', 'aerolinea', 'origen', 'destino'], 'verbose_name': 'Vuelo', 'verbose_name_plural': 'Vuelos'},
        ),
        migrations.AddField(
            model_name='vuelo',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Marcar como vuelo destacado'),
        ),
        migrations.AlterField(
            model_name='paqueteturistico',
            name='ubicacion_mapa_url',
            field=models.URLField(blank=True, help_text='URL de OpenStreetMap (#map=zoom/lat/lon)', max_length=500, null=True, validators=[servicios.models.validate_openstreetmap_url]),
        ),
    ]
