# Generated by Django 6.0.1 on 2026-02-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_alter_vuelo_options_vuelo_destacado_and_more'),
    ]

    operations = [
        # Primero remover el unique_together anterior
        migrations.AlterUniqueTogether(
            name='ciudad',
            unique_together=set(),
        ),
        # Remover campos antiguos de PaisRegion
        migrations.RemoveField(
            model_name='paisregion',
            name='bandera_url',
        ),
        migrations.RemoveField(
            model_name='paisregion',
            name='codigo_pais',
        ),
        # Agregar nuevos campos a Ciudad ANTES de unique_together
        migrations.AddField(
            model_name='ciudad',
            name='codigo_ciudad',
            field=models.CharField(blank=True, help_text='Código IATA de la ciudad (ej: GYE, UIO)', max_length=5),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='latitud',
            field=models.FloatField(blank=True, help_text='Latitud de la ciudad', null=True),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='longitud',
            field=models.FloatField(blank=True, help_text='Longitud de la ciudad', null=True),
        ),
        # Agregar nuevos campos a PaisRegion
        migrations.AddField(
            model_name='paisregion',
            name='bandera_png',
            field=models.URLField(blank=True, help_text='URL de la bandera PNG', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='paisregion',
            name='bandera_svg',
            field=models.URLField(blank=True, help_text='URL de la bandera SVG', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='paisregion',
            name='capital',
            field=models.CharField(blank=True, help_text='Capital del país', max_length=100),
        ),
        migrations.AddField(
            model_name='paisregion',
            name='codigo_iso',
            field=models.CharField(blank=True, help_text='Código ISO de 2 letras (ej: US, EC)', max_length=2),
        ),
        migrations.AddField(
            model_name='paisregion',
            name='codigo_iso3',
            field=models.CharField(blank=True, help_text='Código ISO de 3 letras (ej: USA, ECU)', max_length=3),
        ),
        migrations.AddField(
            model_name='paisregion',
            name='nombre_en',
            field=models.CharField(blank=True, help_text='Nombre en inglés', max_length=100),
        ),
        migrations.AlterField(
            model_name='paisregion',
            name='nombre',
            field=models.CharField(help_text='Nombre en español', max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='nombre',
            field=models.CharField(choices=[('caribe', 'Caribe'), ('sudamerica', 'Sudamérica'), ('centroamerica', 'Centroamérica'), ('norteamerica', 'Norteamérica'), ('europa', 'Europa'), ('medio_oriente', 'Medio Oriente'), ('africa', 'África'), ('asia', 'Asia'), ('oceania', 'Oceanía'), ('ecuador', 'Ecuador')], max_length=50, unique=True),
        ),
        # Remover campo antiguo
        migrations.RemoveField(
            model_name='ciudad',
            name='codigo_aeropuerto',
        ),
        # Ahora sí aplicar el nuevo unique_together con codigo_ciudad
        migrations.AlterUniqueTogether(
            name='ciudad',
            unique_together={('pais', 'codigo_ciudad')},
        ),
    ]
