# Generated by Django 6.0.1 on 2026-02-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_alter_ciudad_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerolinea',
            name='anio_creacion',
            field=models.CharField(blank=True, help_text='Año de creación de la aerolínea', max_length=10),
        ),
        migrations.AddField(
            model_name='aerolinea',
            name='base_aeropuerto',
            field=models.CharField(blank=True, help_text='Aeropuerto base de la aerolínea', max_length=300),
        ),
        migrations.AddField(
            model_name='aerolinea',
            name='brandmark_url',
            field=models.URLField(blank=True, help_text='URL del brandmark/isotipo', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aerolinea',
            name='codigo_icao',
            field=models.CharField(blank=True, help_text='Código ICAO de 3-4 letras (ej: AAL, IBE)', max_length=4),
        ),
        migrations.AlterField(
            model_name='aerolinea',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL del logo completo', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aerolinea',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='codigo_ciudad',
            field=models.CharField(blank=True, help_text='Código ISO de la ciudad (ej: GYE, UIO)', max_length=5),
        ),
    ]
