# Generated by Django 6.0.1 on 2026-03-01 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_aerolinea_nuevos_campos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iata', models.CharField(help_text='Código IATA del aeropuerto (ej: GYE, UIO, MIA)', max_length=3, unique=True)),
                ('codigo_icao', models.CharField(blank=True, help_text='Código ICAO del aeropuerto (ej: SEGU, SEQU)', max_length=4)),
                ('nombre', models.CharField(help_text='Nombre del aeropuerto', max_length=200)),
                ('nombre_ciudad', models.CharField(blank=True, help_text='Nombre de la ciudad (del JSON original)', max_length=100)),
                ('region', models.CharField(blank=True, help_text='Región/Estado', max_length=100)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('elevacion_ft', models.IntegerField(blank=True, help_text='Elevación en pies', null=True)),
                ('zona_horaria', models.CharField(blank=True, help_text='Zona horaria (ej: America/Guayaquil)', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(blank=True, help_text='Ciudad del aeropuerto (si existe en el sistema)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aeropuertos', to='servicios.ciudad')),
                ('pais', models.ForeignKey(help_text='País del aeropuerto', on_delete=django.db.models.deletion.CASCADE, related_name='aeropuertos', to='servicios.paisregion')),
            ],
            options={
                'verbose_name': 'Aeropuerto',
                'verbose_name_plural': 'Aeropuertos',
                'ordering': ['pais', 'nombre'],
            },
        ),
    ]
