# Generated by Django 6.0.1 on 2026-03-21 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0013_aeropuerto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vuelo',
            name='numero_vuelo',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='pdf_url',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='tipo_vuelo',
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_destino', to='servicios.aeropuerto'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_origen', to='servicios.aeropuerto'),
        ),
    ]
