# Generated by Django 6.0.1 on 2026-03-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0014_remove_vuelo_numero_vuelo_remove_vuelo_pdf_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeropuerto',
            name='nombre_ciudad',
            field=models.CharField(blank=True, help_text='Úsalo solo si la ciudad no está en el listado de arriba (ej: Punta Cana, Miami)', max_length=100, verbose_name='Ciudad (Texto libre)'),
        ),
        migrations.AlterField(
            model_name='aeropuerto',
            name='region',
            field=models.CharField(blank=True, help_text='División territorial donde está el aeropuerto (ej: Florida, Guayas, Texas)', max_length=100, verbose_name='Estado / Provincia'),
        ),
    ]
