# Generated by Django 6.0.1 on 2026-03-21 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0015_alter_aeropuerto_nombre_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='aerolinea',
            field=models.ForeignKey(help_text='aerolinea predeterminada', on_delete=django.db.models.deletion.CASCADE, related_name='vuelos', to='servicios.aerolinea'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='duracion',
            field=models.CharField(help_text='duracion media', max_length=50),
        ),
    ]
