# Generated by Django 6.0.1 on 2026-03-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0016_alter_vuelo_aerolinea_alter_vuelo_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentaauto',
            name='ciudad',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='RentaAuto',
        ),
    ]
