# Generated by Django 6.0.1 on 2026-03-21 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0017_remove_rentaauto_ciudad_delete_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='ciudad',
            field=models.ForeignKey(blank=True, help_text='Ciudad del destino (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinos', to='servicios.ciudad'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='pais',
            field=models.ForeignKey(blank=True, help_text='País del destino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinos', to='servicios.paisregion'),
        ),
    ]
