# Generated by Django 6.0.1 on 2026-03-21 19:04

import django.db.models.deletion
import servicios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0018_destino_ciudad_alter_destino_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionDestacados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_vuelos', models.PositiveIntegerField(default=10, help_text='Cantidad máxima de vuelos destacados a enviar en la API particular')),
                ('limite_paquetes', models.PositiveIntegerField(default=10, help_text='Cantidad máxima de paquetes destacados a enviar en la API particular')),
                ('limite_destinos', models.PositiveIntegerField(default=10, help_text='Cantidad máxima de destinos destacados a enviar en la API particular')),
            ],
            options={
                'verbose_name': 'Configuración de Destacados',
                'verbose_name_plural': 'Configuración de Destacados (General)',
            },
        ),
        migrations.RemoveField(
            model_name='destino',
            name='ciudad',
        ),
        migrations.AlterField(
            model_name='destino',
            name='pais',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='aerolinea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos', to='servicios.aerolinea'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='duracion',
            field=models.CharField(help_text='Ej: 1h 45m', max_length=50),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen_url', models.URLField(max_length=500)),
                ('direccion', models.CharField(max_length=300)),
                ('estrellas', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicios', models.TextField(help_text='Servicios separados por comas (Wi-Fi, Piscina, etc.)')),
                ('disponible', models.BooleanField(default=True)),
                ('pdf_url', models.URLField(blank=True, help_text='URL del PDF de Google Drive (se convertirá a /preview automáticamente)', max_length=500, null=True, validators=[servicios.models.validate_google_drive_pdf])),
                ('mensaje_reserva', models.TextField(blank=True, help_text='Mensaje predefinido para reserva/contacto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoteles', to='servicios.destino')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
                'ordering': ['destino', 'nombre'],
            },
            bases=(servicios.models.GoogleDrivePDFMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrdenDestinoDestacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_destinos', to='servicios.configuraciondestacados')),
                ('destino', models.ForeignKey(limit_choices_to={'destacado': True}, on_delete=django.db.models.deletion.CASCADE, to='servicios.destino')),
            ],
            options={
                'verbose_name': 'Orden de Destino Puesto',
                'verbose_name_plural': 'Orden de Destinos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenPaqueteDestacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_paquetes', to='servicios.configuraciondestacados')),
                ('paquete', models.ForeignKey(limit_choices_to={'destacado': True}, on_delete=django.db.models.deletion.CASCADE, to='servicios.paqueteturistico')),
            ],
            options={
                'verbose_name': 'Orden de Paquete Puesto',
                'verbose_name_plural': 'Orden de Paquetes',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenVueloDestacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_vuelos', to='servicios.configuraciondestacados')),
                ('vuelo', models.ForeignKey(limit_choices_to={'destacado': True}, on_delete=django.db.models.deletion.CASCADE, to='servicios.vuelo')),
            ],
            options={
                'verbose_name': 'Orden de Vuelo Puesto',
                'verbose_name_plural': 'Orden de Vuelos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RentaAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('economico', 'Económico'), ('sedan', 'Sedán'), ('suv', 'SUV'), ('lujo', 'Lujo'), ('van', 'Van')], max_length=20)),
                ('ano', models.IntegerField()),
                ('capacidad_pasajeros', models.IntegerField()),
                ('transmision', models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], max_length=20)),
                ('precio_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_url', models.URLField(max_length=500)),
                ('direccion', models.CharField(blank=True, help_text='Dirección específica de recogida', max_length=300)),
                ('caracteristicas', models.TextField(help_text='Características separadas por comas')),
                ('disponible', models.BooleanField(default=True)),
                ('pdf_url', models.URLField(blank=True, help_text='URL del PDF de Google Drive (se convertirá a /preview automáticamente)', max_length=500, null=True, validators=[servicios.models.validate_google_drive_pdf])),
                ('mensaje_reserva', models.TextField(blank=True, help_text='Mensaje predefinido para reserva/contacto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos_renta', to='servicios.ciudad')),
            ],
            options={
                'verbose_name': 'Renta de Auto',
                'verbose_name_plural': 'Renta de Autos',
                'ordering': ['tipo', 'marca'],
            },
            bases=(servicios.models.GoogleDrivePDFMixin, models.Model),
        ),
    ]
