# Generated by Django 6.0.1 on 2026-03-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0019_configuraciondestacados_remove_destino_ciudad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
