# Generated by Django 6.0.1 on 2026-03-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0021_temporada_tipopaquete_tipoviaje_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentaAuto',
        ),
    ]
