# Generated by Django 4.2.30 on 2026-07-20 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0023_destino_ciudad_alter_destino_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaVuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(db_index=True, max_length=10, verbose_name='PNR')),
                ('booking_ref', models.CharField(blank=True, max_length=20, verbose_name='Referencia de reserva')),
                ('stripe_session_id', models.CharField(max_length=200, unique=True, verbose_name='Sesión de Stripe')),
                ('email', models.EmailField(blank=True, max_length=120, verbose_name='Email de contacto')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono de contacto')),
                ('ruta', models.CharField(blank=True, max_length=200, verbose_name='Ruta')),
                ('n_pasajeros', models.PositiveIntegerField(default=1, verbose_name='Número de pasajeros')),
                ('pasajeros', models.JSONField(blank=True, default=list, verbose_name='Pasajeros')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto total')),
                ('moneda', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='CONFIRMADA', max_length=12, verbose_name='Estado')),
                ('sandbox', models.BooleanField(default=False, verbose_name='Sandbox')),
                ('datos', models.JSONField(blank=True, default=dict, verbose_name='Reserva completa (JSON)')),
                ('notas_gestion', models.TextField(blank=True, help_text='Notas internas del asesor sobre esta reserva', verbose_name='Notas de gestión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_vuelo_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='Cancelada por')),
            ],
            options={
                'verbose_name': 'Reserva de Vuelo',
                'verbose_name_plural': 'Reservas de Vuelos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ReservaPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizador', models.CharField(db_index=True, max_length=20, verbose_name='Localizador')),
                ('stripe_session_id', models.CharField(max_length=200, unique=True, verbose_name='Sesión de Stripe')),
                ('paquete_titulo', models.CharField(blank=True, max_length=200, verbose_name='Título del paquete')),
                ('email', models.EmailField(blank=True, max_length=120, verbose_name='Email de contacto')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono de contacto')),
                ('n_personas', models.PositiveIntegerField(default=1, verbose_name='Número de personas')),
                ('fecha_viaje', models.CharField(blank=True, max_length=20, verbose_name='Fecha de viaje')),
                ('viajeros', models.JSONField(blank=True, default=list, verbose_name='Viajeros')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto total')),
                ('moneda', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='CONFIRMADA', max_length=12, verbose_name='Estado')),
                ('sandbox', models.BooleanField(default=False, verbose_name='Sandbox')),
                ('datos', models.JSONField(blank=True, default=dict, verbose_name='Reserva completa (JSON)')),
                ('notas_gestion', models.TextField(blank=True, help_text='Notas internas del asesor sobre esta reserva', verbose_name='Notas de gestión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_paquete_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='Cancelada por')),
                ('paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='servicios.paqueteturistico', verbose_name='Paquete')),
            ],
            options={
                'verbose_name': 'Reserva de Paquete',
                'verbose_name_plural': 'Reservas de Paquetes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
