# Generated by Django 4.2.30 on 2026-07-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0025_grupo_asesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_principal', models.EmailField(default='miltondaviladt@gmail.com', help_text='Correo al que llegan los mensajes de contacto y los avisos de nuevas reservas', max_length=120, verbose_name='Correo principal de notificaciones')),
                ('emails_adicionales', models.TextField(blank=True, help_text='Correos extra separados por comas (opcional). Ej: ventas@corpodg.com, gerencia@corpodg.com', verbose_name='Correos adicionales')),
                ('notificar_contacto', models.BooleanField(default=True, help_text='Enviar correo cuando un cliente use el formulario de contacto', verbose_name='Notificar formulario de contacto')),
                ('notificar_reservas', models.BooleanField(default=True, help_text='Enviar correo cuando se confirme una reserva de vuelo o paquete', verbose_name='Notificar nuevas reservas')),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuración de Notificaciones (Correos)',
            },
        ),
        migrations.AddField(
            model_name='reservapaquete',
            name='revisada',
            field=models.BooleanField(default=False, help_text='Marca la reserva como revisada para quitarla de la notificación del panel', verbose_name='Revisada'),
        ),
        migrations.AddField(
            model_name='reservavuelo',
            name='revisada',
            field=models.BooleanField(default=False, help_text='Marca la reserva como revisada para quitarla de la notificación del panel', verbose_name='Revisada'),
        ),
    ]
