"""
Django settings for corpodg project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'servicios',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS Configuration
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', cast=Csv())

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

ROOT_URLCONF = 'corpodg.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'corpodg.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE'),
    }
}

if config('DB_ENGINE') == 'django.db.backends.sqlite3':
    DATABASES['default']['NAME'] = BASE_DIR / config('DB_NAME', default='db.sqlite3')
else:
    DATABASES['default'].update({
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT')
    })


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('EMAIL_HOST_USER', default='')


# Seat Map mode
# True  -> sandbox (respuestas simuladas)
# False -> Sabre real (Get Seats v3)
SEATMAP_SANDBOX = config('SEATMAP_SANDBOX', default=True, cast=bool)

# Booking / Stripe
BOOKING_SANDBOX = config('BOOKING_SANDBOX', default=True, cast=bool)
# Enviar voucher (boletos + PDF) por correo al confirmar la reserva
BOOKING_SEND_EMAIL = config('BOOKING_SEND_EMAIL', default=True, cast=bool)
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')
FRONTEND_BOOKING_SUCCESS_URL = config('FRONTEND_BOOKING_SUCCESS_URL',
                                     default='http://localhost:5173/reserva/confirmada')
FRONTEND_BOOKING_CANCEL_URL = config('FRONTEND_BOOKING_CANCEL_URL',
                                    default='http://localhost:5173/reserva/cancelada')


WHATSAPP_TOKEN = config('WHATSAPP_TOKEN', default='')
WHATSAPP_PHONE_NUMBER_ID = config('WHATSAPP_PHONE_NUMBER_ID', default='')
WHATSAPP_TEMPLATE_NAME = config('WHATSAPP_TEMPLATE_NAME', default='plantilla_contacto')
WHATSAPP_TEMPLATE_LANGUAGE = config('WHATSAPP_TEMPLATE_LANGUAGE', default='es_EC')
WHATSAPP_RECIPIENT_NUMBER = config('WHATSAPP_RECIPIENT_NUMBER', default='')  # Número al que se enviarán las notificaciones

#SABRE API CONFIGURATION

CLIENT_ID = config('CLIENT_ID', default='')
CLIENT_SECRET = config('CLIENT_SECRET', default='')
SABRE_AUTH_URL = config('SABRE_AUTH_URL', default='https://api.cert.platform.sabre.com/v2/auth/token')
SABRE_TOKEN_REFRESH_MARGIN = config('SABRE_TOKEN_REFRESH_MARGIN', default=60, cast=int)

# CHATBOT AI CONFIGURATION (Groq)
GROQ_API_KEY = config('GROQ_API_KEY', default='')


# Admin dashboard (django-jazzmin) — branding CorpoDG
JAZZMIN_SETTINGS = {
    "site_title": "CorpoDG Admin",
    "site_header": "CorpoDG",
    "site_brand": "CorpoDG Trip593",
    "site_logo": "logo.png",
    "site_logo_classes": "brand-image-corpodg",
    "site_icon": "logo.png",
    "login_logo": "logo.png",
    "login_logo_dark": None,
    "welcome_sign": "Bienvenido al panel de administración de CorpoDG",
    "copyright": "Corporación Dávila & Granda",
    "show_ui_builder": False,
    "navigation_expanded": True,
    "language_chooser": False,
    "custom_css": "css/admin-corpodg.css",
    "custom_js": "js/admin-corpodg.js",
    "topmenu_links": [
        {"name": "Dashboard", "url": "/admin/dashboard/"},
        {"name": "Exportar CSV", "url": "/admin/exportar-reservas/"},
        {"name": "Ver el sitio", "url": "/", "new_window": True},
    ],
    "icons": {
        "auth.Group": "fas fa-users-cog",
        "auth.User": "fas fa-user",
        "authtoken.TokenProxy": "fas fa-key",
        "servicios.Cliente": "fas fa-user-tie",
        "servicios.Solicitud": "fas fa-inbox",
        "servicios.Destino": "fas fa-map-marker-alt",
        "servicios.Vuelo": "fas fa-plane",
        "servicios.Region": "fas fa-globe-americas",
        "servicios.PaisRegion": "fas fa-flag",
        "servicios.Ciudad": "fas fa-city",
        "servicios.Aerolinea": "fas fa-plane-departure",
        "servicios.Aeropuerto": "fas fa-plane-arrival",
        "servicios.PaqueteTuristico": "fas fa-suitcase-rolling",
        "servicios.ConfiguracionDestacados": "fas fa-star",
        "servicios.TipoPaquete": "fas fa-tags",
        "servicios.Temporada": "fas fa-calendar-alt",
        "servicios.TipoViaje": "fas fa-route",
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_flat_style": True,
    "sidebar_nav_child_indent": True,
    "actions_sticky_top": True,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success",
    },
}